vich_uploader:
    db_driver: orm

    mappings:
        professionals_image:
            uri_prefix: /images/professionals
            upload_destination: '%kernel.project_dir%/public/images/professionals'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        services_image:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        home_image:
            uri_prefix: /images/home
            upload_destination: '%kernel.project_dir%/public/images/home'
            namer: Vich\UploaderBundle\Naming\UniqidNamer



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
